const TRANSLATIONS = {
  hi: {
    loading: 'GramAI लोड हो रहा है...', subtitle: 'ऑफ़लाइन AI सहायक', selectTopic: 'विषय चुनें',
    catAgri: 'कृषि', catHealth: 'स्वास्थ्य', catEdu: 'शिक्षा', catSchemes: 'सरकारी योजना',
    greeting: 'नमस्ते!', welcomeMsg: 'मैं GramAI हूँ। कृषि, स्वास्थ्य, शिक्षा या सरकारी योजनाओं के बारे में पूछें।',
    welcomeHint: 'बोलकर या लिखकर सवाल पूछ सकते हैं।', inputPlaceholder: 'यहाँ सवाल लिखें...',
    online: 'चालू', offline: 'ऑफ़लाइन', speak: 'बोलिए...', recognizing: 'आवाज़ पहचानी जा रही है...',
    recognized: 'पहचाना', noSpeech: 'आवाज़ नहीं पहचानी जा सकी। दोबारा बोलें।',
    voiceUnavailable: 'वॉइस सेवा उपलब्ध नहीं है। कृपया टाइप करें।',
    micUnavailable: 'माइक्रोफोन उपलब्ध नहीं है', error: 'कुछ गड़बड़ हुई। कृपया दोबारा कोशिश करें।',
    allTopics: 'सभी विषय दिखाए जा रहे हैं', topicSelected: 'विषय चुना गया',
    llmUnavailable: 'AI मॉडल उपलब्ध नहीं है। ज्ञान आधार से जवाब दिया जाएगा।',
    langChanged: 'भाषा बदली गई', source: 'स्रोत',
    installTitle: 'GramAI इंस्टॉल करें', installDesc: 'ऐप को अपने फ़ोन में इंस्टॉल करें', installBtn: 'इंस्टॉल',
    quickWheat: 'गेहूं की खेती', quickPM: 'PM-KISAN', quickFever: 'बुखार का इलाज',
    quickScholar: 'छात्रवृत्ति', quickOrganic: 'जैविक खेती', quickAyush: 'आयुष्मान कार्ड',
    onlineMode: 'ऑनलाइन AI', offlineMode: 'ऑफलाइन ज्ञान',
    onlineNotConfigured: 'ऑनलाइन AI कॉन्फ़िगर नहीं है। .env में OPENROUTER_API_KEY सेट करें।',
    onlineGreeting: '🤖 ऑनलाइन AI मोड',
    onlineWelcome: 'मैं GramAI हूँ। कुछ भी पूछें - मैं हर सवाल का जवाब दे सकता हूँ!',
    onlineHint: 'इंटरनेट से AI चैटबॉट सक्रिय है। कुछ भी पूछें!',
  },
  en: {
    loading: 'GramAI is loading...', subtitle: 'Offline AI Assistant', selectTopic: 'Choose a Topic',
    catAgri: 'Agriculture', catHealth: 'Health', catEdu: 'Education', catSchemes: 'Govt. Schemes',
    greeting: 'Hello!', welcomeMsg: "I'm GramAI. Ask me about agriculture, health, education, or government schemes.",
    welcomeHint: 'You can ask by speaking or typing.', inputPlaceholder: 'Type your question here...',
    online: 'Online', offline: 'Offline', speak: 'Speak now...', recognizing: 'Recognizing speech...',
    recognized: 'Recognized', noSpeech: 'Could not recognize speech. Try again.',
    voiceUnavailable: 'Voice service unavailable. Please type.',
    micUnavailable: 'Microphone not available', error: 'Something went wrong. Try again.',
    allTopics: 'Showing all topics', topicSelected: 'topic selected',
    llmUnavailable: 'AI model not available. Answering from knowledge base.',
    langChanged: 'Language changed', source: 'Source',
    installTitle: 'Install GramAI', installDesc: 'Add this app to your home screen', installBtn: 'Install',
    quickWheat: 'Wheat farming', quickPM: 'PM-KISAN', quickFever: 'Fever treatment',
    quickScholar: 'Scholarship', quickOrganic: 'Organic farming', quickAyush: 'Ayushman Card',
    onlineMode: 'Online AI', offlineMode: 'Offline KB',
    onlineNotConfigured: 'Online AI not configured. Set OPENROUTER_API_KEY in .env file.',
    onlineGreeting: '🤖 Online AI Mode',
    onlineWelcome: "I'm GramAI. Ask me anything - I can answer every question!",
    onlineHint: 'AI chatbot is active via internet. Ask anything!',
  },
  // Hinglish — Hindi written in Roman script
  hg: {
    loading: 'GramAI load ho raha hai...', subtitle: 'Offline AI Sahayak', selectTopic: 'Topic choose karo',
    catAgri: 'Kheti', catHealth: 'Health', catEdu: 'Padhai', catSchemes: 'Sarkari Yojana',
    greeting: 'Namaste!', welcomeMsg: 'Main GramAI hoon. Kheti, health, padhai ya sarkari yojana ke baare mein poocho.',
    welcomeHint: 'Bol ke ya likh ke sawaal pooch sakte ho.', inputPlaceholder: 'Yahan sawaal likho...',
    online: 'Online', offline: 'Offline', speak: 'Bolo...', recognizing: 'Awaaz pehchaan raha hai...',
    recognized: 'Pehchaan liya', noSpeech: 'Awaaz nahi pehchaani. Dobara bolo.',
    voiceUnavailable: 'Voice service nahi hai. Type karo.',
    micUnavailable: 'Mic available nahi hai', error: 'Kuch gadbad hui. Dobara try karo.',
    allTopics: 'Sab topics dikh rahe hain', topicSelected: 'Topic select hua',
    llmUnavailable: 'AI model available nahi. Knowledge base se jawab milega.',
    langChanged: 'Language badal gayi', source: 'Source',
    installTitle: 'GramAI Install karo', installDesc: 'App apne phone mein install karo', installBtn: 'Install',
    quickWheat: 'Gehun ki kheti', quickPM: 'PM-KISAN', quickFever: 'Bukhar ka ilaaj',
    quickScholar: 'Scholarship', quickOrganic: 'Organic kheti', quickAyush: 'Ayushman Card',
    onlineMode: 'Online AI', offlineMode: 'Offline KB',
    onlineNotConfigured: 'Online AI set nahi hai.',
    onlineGreeting: '🤖 Online AI Mode',
    onlineWelcome: 'Main GramAI hoon. Kuch bhi poocho - har sawaal ka jawaab dunga!',
    onlineHint: 'Internet se AI chatbot active hai. Kuch bhi poocho!',
  },
  ta: { loading: 'GramAI ஏற்றப்படுகிறது...', subtitle: 'ஆஃப்லைன் AI உதவி', selectTopic: 'தலைப்பை தேர்ந்தெடுக்கவும்', catAgri: 'விவசாயம்', catHealth: 'சுகாதாரம்', catEdu: 'கல்வி', catSchemes: 'அரசு திட்டங்கள்', greeting: 'வணக்கம்!', welcomeMsg: 'நான் GramAI. விவசாயம், சுகாதாரம், கல்வி பற்றி கேளுங்கள்.', welcomeHint: 'பேசி அல்லது தட்டச்சு செய்யுங்கள்.', inputPlaceholder: 'கேள்வியை எழுதுங்கள்...', online: 'இணைப்பு', offline: 'ஆஃப்லைன்', speak: 'பேசுங்கள்...', recognizing: 'குரல் அடையாளம்...', recognized: 'அடையாளம்', noSpeech: 'குரல் அடையாளம் காண முடியவில்லை.', voiceUnavailable: 'குரல் சேவை கிடைக்கவில்லை.', micUnavailable: 'மைக்ரோஃபோன் கிடைக்கவில்லை', error: 'தவறு நடந்தது.', allTopics: 'அனைத்து தலைப்புகள்', topicSelected: 'தலைப்பு தேர்வு', llmUnavailable: 'AI மாடல் கிடைக்கவில்லை.', langChanged: 'மொழி மாற்றம்', source: 'மூலம்', installTitle: 'GramAI நிறுவு', installDesc: 'ஆப்பை நிறுவுங்கள்', installBtn: 'நிறுவு', quickWheat: 'கோதுமை', quickPM: 'PM-KISAN', quickFever: 'காய்ச்சல்', quickScholar: 'உதவித்தொகை', quickOrganic: 'இயற்கை வேளாண்மை', quickAyush: 'ஆயுஷ்மான்' },
  te: { loading: 'GramAI లోడ్...', subtitle: 'ఆఫ్‌లైన్ AI సహాయం', selectTopic: 'అంశం ఎంచుకోండి', catAgri: 'వ్యవసాయం', catHealth: 'ఆరోగ్యం', catEdu: 'విద్య', catSchemes: 'ప్రభుత్వ పథకాలు', greeting: 'నమస్కారం!', welcomeMsg: 'నేను GramAI. వ్యవసాయం, ఆరోగ్యం, విద్య గురించి అడగండి.', welcomeHint: 'మాట్లాడి లేదా టైప్ చేయండి.', inputPlaceholder: 'ప్రశ్న రాయండి...', online: 'ఆన్‌లైన్', offline: 'ఆఫ్‌లైన్', speak: 'మాట్లాడండి...', recognizing: 'గుర్తిస్తోంది...', recognized: 'గుర్తించబడింది', noSpeech: 'గుర్తించలేకపోయింది.', voiceUnavailable: 'వాయిస్ సేవ లేదు.', micUnavailable: 'మైక్ లేదు', error: 'తప్పు జరిగింది.', allTopics: 'అన్ని అంశాలు', topicSelected: 'అంశం ఎంపిక', llmUnavailable: 'AI మోడల్ లేదు.', langChanged: 'భాష మారింది', source: 'మూలం', installTitle: 'GramAI ఇన్‌స్టాల్', installDesc: 'యాప్ ఇన్‌స్టాల్ చేయండి', installBtn: 'ఇన్‌స్టాల్', quickWheat: 'గోధుమ', quickPM: 'PM-KISAN', quickFever: 'జ్వరం', quickScholar: 'స్కాలర్‌షిప్', quickOrganic: 'సేంద్రీయ', quickAyush: 'ఆయుష్మాన్' },
  bn: { loading: 'GramAI লোড হচ্ছে...', subtitle: 'অফলাইন AI সহকারী', selectTopic: 'বিষয় নির্বাচন', catAgri: 'কৃষি', catHealth: 'স্বাস্থ্য', catEdu: 'শিক্ষা', catSchemes: 'সরকারি প্রকল্প', greeting: 'নমস্কার!', welcomeMsg: 'আমি GramAI। কৃষি, স্বাস্থ্য, শিক্ষা সম্পর্কে জিজ্ঞাসা করুন।', welcomeHint: 'বলে বা লিখে প্রশ্ন করুন।', inputPlaceholder: 'প্রশ্ন লিখুন...', online: 'অনলাইন', offline: 'অফলাইন', speak: 'বলুন...', recognizing: 'শনাক্ত করা হচ্ছে...', recognized: 'শনাক্ত', noSpeech: 'শনাক্ত করা যায়নি।', voiceUnavailable: 'ভয়েস সেবা নেই.', micUnavailable: 'মাইক্রোফোন নেই', error: 'সমস্যা হয়েছে।', allTopics: 'সব বিষয়', topicSelected: 'বিষয় নির্বাচিত', llmUnavailable: 'AI মডেল নেই।', langChanged: 'ভাষা পরিবর্তন', source: 'উৎস', installTitle: 'GramAI ইনস্টল', installDesc: 'অ্যাপ ইনস্টল করুন', installBtn: 'ইনস্টল', quickWheat: 'গম', quickPM: 'PM-KISAN', quickFever: 'জ্বর', quickScholar: 'বৃত্তি', quickOrganic: 'জৈব চাষ', quickAyush: 'আয়ুষ্মান' },
  mr: { loading: 'GramAI लोड होत आहे...', subtitle: 'ऑफलाइन AI सहाय्यक', selectTopic: 'विषय निवडा', catAgri: 'शेती', catHealth: 'आरोग्य', catEdu: 'शिक्षण', catSchemes: 'सरकारी योजना', greeting: 'नमस्कार!', welcomeMsg: 'मी GramAI. शेती, आरोग्य, शिक्षण बद्दल विचारा.', welcomeHint: 'बोलून किंवा टाइप करा.', inputPlaceholder: 'प्रश्न लिहा...', online: 'ऑनलाइन', offline: 'ऑफलाइन', speak: 'बोला...', recognizing: 'ओळखत आहे...', recognized: 'ओळखले', noSpeech: 'ओळखता आले नाही.', voiceUnavailable: 'व्हॉइस सेवा नाही.', micUnavailable: 'माइक नाही', error: 'चूक झाली.', allTopics: 'सर्व विषय', topicSelected: 'विषय निवडला', llmUnavailable: 'AI मॉडेल नाही.', langChanged: 'भाषा बदलली', source: 'स्रोत', installTitle: 'GramAI इंस्टॉल', installDesc: 'अॅप इंस्टॉल करा', installBtn: 'इंस्टॉल', quickWheat: 'गहू', quickPM: 'PM-KISAN', quickFever: 'ताप', quickScholar: 'शिष्यवृत्ती', quickOrganic: 'सेंद्रिय शेती', quickAyush: 'आयुष्मान' },
  gu: { loading: 'GramAI લોડ થઈ રહ્યું...', subtitle: 'ઑફલાઇન AI સહાયક', selectTopic: 'વિષય પસંદ કરો', catAgri: 'ખેતી', catHealth: 'આરોગ્ય', catEdu: 'શિક્ષણ', catSchemes: 'સરકારી યોજના', greeting: 'નમસ્તે!', welcomeMsg: 'હું GramAI છું. ખેતી, આરોગ્ય, શિક્ષણ વિશે પૂછો.', welcomeHint: 'બોલીને કે ટાઇપ કરીને પૂછો.', inputPlaceholder: 'પ્રશ્ન લખો...', online: 'ઑનલાઇન', offline: 'ઑફલાઇન', speak: 'બોલો...', recognizing: 'ઓળખી રહ્યા...', recognized: 'ઓળખાયું', noSpeech: 'ઓળખી ન શક્યા.', voiceUnavailable: 'વૉઇસ સેવા નથી.', micUnavailable: 'માઇક નથી', error: 'ખોટું થયું.', allTopics: 'બધા વિષયો', topicSelected: 'વિષય પસંદ', llmUnavailable: 'AI મોડેલ નથી.', langChanged: 'ભાષા બદલાઈ', source: 'સ્રોત', installTitle: 'GramAI ઇન્સ્ટોલ', installDesc: 'એપ ઇન્સ્ટોલ કરો', installBtn: 'ઇન્સ્ટોલ', quickWheat: 'ઘઉં', quickPM: 'PM-KISAN', quickFever: 'તાવ', quickScholar: 'શિષ્યવૃત્તિ', quickOrganic: 'ઓર્ગેનિક', quickAyush: 'આયુષ્માન' },
  kn: { loading: 'GramAI ಲೋಡ್...', subtitle: 'ಆಫ್‌ಲೈನ್ AI ಸಹಾಯ', selectTopic: 'ವಿಷಯ ಆಯ್ಕೆ', catAgri: 'ಕೃಷಿ', catHealth: 'ಆರೋಗ್ಯ', catEdu: 'ಶಿಕ್ಷಣ', catSchemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆ', greeting: 'ನಮಸ್ಕಾರ!', welcomeMsg: 'ನಾನು GramAI. ಕೃಷಿ, ಆರೋಗ್ಯ, ಶಿಕ್ಷಣ ಬಗ್ಗೆ ಕೇಳಿ.', welcomeHint: 'ಮಾತನಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ.', inputPlaceholder: 'ಪ್ರಶ್ನೆ ಬರೆಯಿರಿ...', online: 'ಆನ್‌ಲೈನ್', offline: 'ಆಫ್‌ಲೈನ್', speak: 'ಮಾತನಾಡಿ...', recognizing: 'ಗುರುತಿಸುತ್ತಿದೆ...', recognized: 'ಗುರುತಿಸಿದೆ', noSpeech: 'ಗುರುತಿಸಲಿಲ್ಲ.', voiceUnavailable: 'ಧ್ವನಿ ಸೇವೆ ಇಲ್ಲ.', micUnavailable: 'ಮೈಕ್ ಇಲ್ಲ', error: 'ತಪ್ಪಾಯಿತು.', allTopics: 'ಎಲ್ಲಾ ವಿಷಯ', topicSelected: 'ವಿಷಯ ಆಯ್ಕೆ', llmUnavailable: 'AI ಮಾಡೆಲ್ ಇಲ್ಲ.', langChanged: 'ಭಾಷೆ ಬದಲಾಯಿತು', source: 'ಮೂಲ', installTitle: 'GramAI ಇನ್‌ಸ್ಟಾಲ್', installDesc: 'ಆ್ಯಪ್ ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿ', installBtn: 'ಇನ್‌ಸ್ಟಾಲ್', quickWheat: 'ಗೋಧಿ', quickPM: 'PM-KISAN', quickFever: 'ಜ್ವರ', quickScholar: 'ವಿದ್ಯಾರ್ಥಿ', quickOrganic: 'ಸಾವಯವ', quickAyush: 'ಆಯುಷ್ಮಾನ್' },
  ml: { loading: 'GramAI ലോഡ്...', subtitle: 'ഓഫ്‌ലൈൻ AI സഹായി', selectTopic: 'വിഷയം തിരഞ്ഞെടുക്കുക', catAgri: 'കൃഷി', catHealth: 'ആരോഗ്യം', catEdu: 'വിദ്യാഭ്യാസം', catSchemes: 'സർക്കാർ പദ്ധതികൾ', greeting: 'നമസ്കാരം!', welcomeMsg: 'ഞാൻ GramAI. കൃഷി, ആരോഗ്യം, വിദ്യാഭ്യാസം ചോദിക്കൂ.', welcomeHint: 'പറയുക അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യുക.', inputPlaceholder: 'ചോദ്യം ടൈപ്പ് ചെയ്യുക...', online: 'ഓൺലൈൻ', offline: 'ഓഫ്‌ലൈൻ', speak: 'സംസാരിക്കുക...', recognizing: 'തിരിച്ചറിയുന്നു...', recognized: 'തിരിച്ചറിഞ്ഞു', noSpeech: 'തിരിച്ചറിഞ്ഞില്ല.', voiceUnavailable: 'വോയ്സ് സേവനം ഇല്ല.', micUnavailable: 'മൈക്ക് ഇല്ല', error: 'തെറ്റ് സംഭവിച്ചു.', allTopics: 'എല്ലാ വിഷയങ്ങൾ', topicSelected: 'വിഷയം തിരഞ്ഞെടുത്തു', llmUnavailable: 'AI മോഡൽ ഇല്ല.', langChanged: 'ഭാഷ മാറ്റി', source: 'ഉറവിടം', installTitle: 'GramAI ഇൻസ്റ്റാൾ', installDesc: 'ആപ്പ് ഇൻസ്റ്റാൾ ചെയ്യൂ', installBtn: 'ഇൻസ്റ്റാൾ', quickWheat: 'ഗോതമ്പ്', quickPM: 'PM-KISAN', quickFever: 'പനി', quickScholar: 'സ്കോളർഷിപ്പ്', quickOrganic: 'ജൈവകൃഷി', quickAyush: 'ആയുഷ്മാൻ' },
  pa: { loading: 'GramAI ਲੋਡ ਹੋ ਰਿਹਾ...', subtitle: 'ਆਫ਼ਲਾਈਨ AI ਸਹਾਇਕ', selectTopic: 'ਵਿਸ਼ਾ ਚੁਣੋ', catAgri: 'ਖੇਤੀ', catHealth: 'ਸਿਹਤ', catEdu: 'ਸਿੱਖਿਆ', catSchemes: 'ਸਰਕਾਰੀ ਯੋਜਨਾ', greeting: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ!', welcomeMsg: 'ਮੈਂ GramAI ਹਾਂ। ਖੇਤੀ, ਸਿਹਤ, ਸਿੱਖਿਆ ਬਾਰੇ ਪੁੱਛੋ।', welcomeHint: 'ਬੋਲ ਕੇ ਜਾਂ ਲਿਖ ਕੇ ਪੁੱਛੋ।', inputPlaceholder: 'ਸਵਾਲ ਲਿਖੋ...', online: 'ਔਨਲਾਈਨ', offline: 'ਆਫ਼ਲਾਈਨ', speak: 'ਬੋਲੋ...', recognizing: 'ਪਛਾਣ ਰਿਹਾ...', recognized: 'ਪਛਾਣਿਆ', noSpeech: 'ਪਛਾਣ ਨਹੀਂ ਹੋਈ।', voiceUnavailable: 'ਵੌਇਸ ਸੇਵਾ ਨਹੀਂ.', micUnavailable: 'ਮਾਈਕ ਨਹੀਂ', error: 'ਗਲਤੀ ਹੋਈ।', allTopics: 'ਸਾਰੇ ਵਿਸ਼ੇ', topicSelected: 'ਵਿਸ਼ਾ ਚੁਣਿਆ', llmUnavailable: 'AI ਮਾਡਲ ਨਹੀਂ।', langChanged: 'ਭਾਸ਼ਾ ਬਦਲੀ', source: 'ਸਰੋਤ', installTitle: 'GramAI ਇੰਸਟਾਲ', installDesc: 'ਐਪ ਇੰਸਟਾਲ ਕਰੋ', installBtn: 'ਇੰਸਟਾਲ', quickWheat: 'ਕਣਕ', quickPM: 'PM-KISAN', quickFever: 'ਬੁਖ਼ਾਰ', quickScholar: 'ਵਜ਼ੀਫ਼ਾ', quickOrganic: 'ਜੈਵਿਕ ਖੇਤੀ', quickAyush: 'ਆਯੁਸ਼ਮਾਨ' },
  // Urdu
  ur: { loading: '...GramAI لوڈ ہو رہا ہے', subtitle: 'آف لائن AI معاون', selectTopic: 'موضوع چنیں', catAgri: 'زراعت', catHealth: 'صحت', catEdu: 'تعلیم', catSchemes: 'سرکاری اسکیم', greeting: '!السلام علیکم', welcomeMsg: 'میں GramAI ہوں۔ زراعت، صحت، تعلیم کے بارے میں پوچھیں۔', welcomeHint: 'بول کر یا لکھ کر سوال پوچھیں۔', inputPlaceholder: '...یہاں سوال لکھیں', online: 'آنلائن', offline: 'آف لائن', speak: '...بولیے', recognizing: '...آواز پہچانی جا رہی ہے', recognized: 'پہچانا', noSpeech: 'آواز نہیں پہچانی جا سکی۔', voiceUnavailable: 'وائس سروس دستیاب نہیں۔', micUnavailable: 'مائیکروفون دستیاب نہیں', error: 'کچھ غلطی ہوئی۔', allTopics: 'سب موضوعات', topicSelected: 'موضوع منتخب', llmUnavailable: 'AI ماڈل دستیاب نہیں۔', langChanged: 'زبان بدلی', source: 'ماخذ', installTitle: 'GramAI انسٹال', installDesc: 'ایپ انسٹال کریں', installBtn: 'انسٹال', quickWheat: 'گندم', quickPM: 'PM-KISAN', quickFever: 'بخار', quickScholar: 'وظیفہ', quickOrganic: 'نامیاتی کھیتی', quickAyush: 'آیوشمان' },
  // Odia
  or: { loading: 'GramAI ଲୋଡ୍ ହେଉଛି...', subtitle: 'ଅଫଲାଇନ AI ସହାୟକ', selectTopic: 'ବିଷୟ ବାଛନ୍ତୁ', catAgri: 'କୃଷି', catHealth: 'ସ୍ୱାସ୍ଥ୍ୟ', catEdu: 'ଶିକ୍ଷା', catSchemes: 'ସରକାରୀ ଯୋଜନା', greeting: 'ନମସ୍କାର!', welcomeMsg: 'ମୁଁ GramAI। କୃଷି, ସ୍ୱାସ୍ଥ୍ୟ, ଶିକ୍ଷା ବିଷୟରେ ପଚାରନ୍ତୁ।', welcomeHint: 'କହି ବା ଲେଖି ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ।', inputPlaceholder: 'ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ...', online: 'ଅନଲାଇନ', offline: 'ଅଫଲାଇନ', speak: 'କୁହନ୍ତୁ...', recognizing: 'ଚିହ୍ନଟ ହେଉଛି...', recognized: 'ଚିହ୍ନଟ', noSpeech: 'ଚିହ୍ନଟ ହେଲା ନାହିଁ।', voiceUnavailable: 'ଭଏସ ସେବା ନାହିଁ।', micUnavailable: 'ମାଇକ ନାହିଁ', error: 'ଭୁଲ ହେଲା।', allTopics: 'ସବୁ ବିଷୟ', topicSelected: 'ବିଷୟ ବଛାଗଲା', llmUnavailable: 'AI ମଡେଲ ନାହିଁ।', langChanged: 'ଭାଷା ବଦଳିଲା', source: 'ଉତ୍ସ', installTitle: 'GramAI ଇନଷ୍ଟଲ', installDesc: 'ଆପ ଇନଷ୍ଟଲ କରନ୍ତୁ', installBtn: 'ଇନଷ୍ଟଲ', quickWheat: 'ଗହମ', quickPM: 'PM-KISAN', quickFever: 'ଜ୍ୱର', quickScholar: 'ବୃତ୍ତି', quickOrganic: 'ଜୈବିକ ଚାଷ', quickAyush: 'ଆୟୁଷ୍ମାନ' },
  // Assamese
  as: { loading: 'GramAI লোড হৈ আছে...', subtitle: 'অফলাইন AI সহায়ক', selectTopic: 'বিষয় বাছক', catAgri: 'কৃষি', catHealth: 'স্বাস্থ্য', catEdu: 'শিক্ষা', catSchemes: 'চৰকাৰী আঁচনি', greeting: 'নমস্কাৰ!', welcomeMsg: 'মই GramAI। কৃষি, স্বাস্থ্য, শিক্ষা বিষয়ে সুধিব পাৰে।', welcomeHint: 'কৈ বা লিখি প্ৰশ্ন কৰক।', inputPlaceholder: 'প্ৰশ্ন লিখক...', online: 'অনলাইন', offline: 'অফলাইন', speak: 'কওক...', recognizing: 'চিনাক্ত কৰি আছে...', recognized: 'চিনাক্ত', noSpeech: 'চিনাক্ত কৰিব নোৱাৰিলে।', voiceUnavailable: 'ভইচ সেৱা নাই।', micUnavailable: 'মাইক নাই', error: 'ভুল হ\'ল।', allTopics: 'সকলো বিষয়', topicSelected: 'বিষয় বাছনি', llmUnavailable: 'AI মডেল নাই।', langChanged: 'ভাষা সলনি', source: 'উৎস', installTitle: 'GramAI ইনষ্টল', installDesc: 'এপ ইনষ্টল কৰক', installBtn: 'ইনষ্টল', quickWheat: 'ঘেঁহু', quickPM: 'PM-KISAN', quickFever: 'জ্বৰ', quickScholar: 'বৃত্তি', quickOrganic: 'জৈৱিক খেতি', quickAyush: 'আয়ুষ্মান' },
  // Nepali
  ne: { loading: 'GramAI लोड हुँदैछ...', subtitle: 'अफलाइन AI सहायक', selectTopic: 'विषय छान्नुहोस्', catAgri: 'कृषि', catHealth: 'स्वास्थ्य', catEdu: 'शिक्षा', catSchemes: 'सरकारी योजना', greeting: 'नमस्ते!', welcomeMsg: 'म GramAI हुँ। कृषि, स्वास्थ्य, शिक्षा बारे सोध्नुहोस्।', welcomeHint: 'बोलेर वा टाइप गरेर सोध्नुहोस्।', inputPlaceholder: 'प्रश्न लेख्नुहोस्...', online: 'अनलाइन', offline: 'अफलाइन', speak: 'बोल्नुहोस्...', recognizing: 'पहिचान गर्दै...', recognized: 'पहिचान भयो', noSpeech: 'पहिचान हुन सकेन।', voiceUnavailable: 'भ्वाइस सेवा छैन।', micUnavailable: 'माइक छैन', error: 'गल्ती भयो।', allTopics: 'सबै विषय', topicSelected: 'विषय छानियो', llmUnavailable: 'AI मोडेल छैन।', langChanged: 'भाषा परिवर्तन', source: 'स्रोत', installTitle: 'GramAI इन्स्टल', installDesc: 'एप इन्स्टल गर्नुहोस्', installBtn: 'इन्स्टल', quickWheat: 'गहुँ', quickPM: 'PM-KISAN', quickFever: 'ज्वरो', quickScholar: 'छात्रवृत्ति', quickOrganic: 'जैविक खेती', quickAyush: 'आयुष्मान' },
  // Konkani
  kok: { loading: 'GramAI लोड जाता...', subtitle: 'ऑफलाइन AI सहाय्यक', selectTopic: 'विषय वेंचून काडात', catAgri: 'शेतकी', catHealth: 'भलायकी', catEdu: 'शिक्षण', catSchemes: 'सरकारी येवजण', greeting: 'नमस्कार!', welcomeMsg: 'हांव GramAI। शेतकी, भलायकी, शिक्षण विशीं विचारात.', welcomeHint: 'उलोवन वा बरोवन विचारात.', inputPlaceholder: 'सवाल बरयात...', online: 'ऑनलाइन', offline: 'ऑफलाइन', speak: 'उलयात...', recognizing: 'वळखता...', recognized: 'वळखलें', noSpeech: 'वळखूंक जालें ना.', voiceUnavailable: 'व्हॉइस सेवा ना.', micUnavailable: 'माइक ना', error: 'चूक जाली.', allTopics: 'सगळे विषय', topicSelected: 'विषय वेंचलो', llmUnavailable: 'AI मॉडेल ना.', langChanged: 'भास बदलली', source: 'मूळ', installTitle: 'GramAI इन्स्टॉल', installDesc: 'ॲप इन्स्टॉल करात', installBtn: 'इन्स्टॉल', quickWheat: 'गंव', quickPM: 'PM-KISAN', quickFever: 'ताप', quickScholar: 'शिश्यवृत्ती', quickOrganic: 'सेंद्रीय शेतकी', quickAyush: 'आयुष्मान' },
  // Dogri
  doi: { loading: 'GramAI लोड हो रहा ऐ...', subtitle: 'ऑफलाइन AI सहायक', selectTopic: 'विषय चुणो', catAgri: 'खेती', catHealth: 'सेहत', catEdu: 'पढ़ाई', catSchemes: 'सरकारी योजना', greeting: 'नमस्कार!', welcomeMsg: 'मैं GramAI आं। खेती, सेहत, पढ़ाई दे बारे च पुच्छो।', welcomeHint: 'बोली करी या लिखी करी पुच्छो।', inputPlaceholder: 'सवाल लिखो...', online: 'ऑनलाइन', offline: 'ऑफलाइन', speak: 'बोलो...', recognizing: 'पहचान रहे आं...', recognized: 'पहचान लिया', noSpeech: 'पहचान नी होई।', voiceUnavailable: 'वॉइस सेवा नी ऐ।', micUnavailable: 'माइक नी ऐ', error: 'कुश गलत होई गेआ।', allTopics: 'सारे विषय', topicSelected: 'विषय चुणेआ', llmUnavailable: 'AI मॉडल नी ऐ।', langChanged: 'भाषा बदली', source: 'स्रोत', installTitle: 'GramAI इंस्टॉल', installDesc: 'ऐप इंस्टॉल करो', installBtn: 'इंस्टॉल', quickWheat: 'कणक', quickPM: 'PM-KISAN', quickFever: 'बुखार', quickScholar: 'वजीफा', quickOrganic: 'जैविक खेती', quickAyush: 'आयुष्मान' },
  // Maithili
  mai: { loading: 'GramAI लोड भऽ रहल अछि...', subtitle: 'ऑफलाइन AI सहायक', selectTopic: 'विषय चुनू', catAgri: 'खेती', catHealth: 'स्वास्थ्य', catEdu: 'शिक्षा', catSchemes: 'सरकारी योजना', greeting: 'प्रणाम!', welcomeMsg: 'हम GramAI छी। खेती, स्वास्थ्य, शिक्षा बारे मे पुछू।', welcomeHint: 'बाजि कऽ या लिखि कऽ पुछू।', inputPlaceholder: 'सवाल लिखू...', online: 'ऑनलाइन', offline: 'ऑफलाइन', speak: 'बाजू...', recognizing: 'पहचान भऽ रहल अछि...', recognized: 'पहचान भेल', noSpeech: 'पहचान नहि भेल।', voiceUnavailable: 'वॉइस सेवा नहि अछि।', micUnavailable: 'माइक नहि अछि', error: 'किछु गड़बड़ भेल।', allTopics: 'सभ विषय', topicSelected: 'विषय चुनल गेल', llmUnavailable: 'AI मॉडल नहि अछि।', langChanged: 'भाषा बदलल', source: 'स्रोत', installTitle: 'GramAI इंस्टॉल', installDesc: 'ऐप इंस्टॉल करू', installBtn: 'इंस्टॉल', quickWheat: 'गहूम', quickPM: 'PM-KISAN', quickFever: 'बोखार', quickScholar: 'छात्रवृत्ति', quickOrganic: 'जैविक खेती', quickAyush: 'आयुष्मान' },
  // Sanskrit
  sa: { loading: 'GramAI लोड् भवति...', subtitle: 'अनालैन AI सहायकः', selectTopic: 'विषयं चिनोतु', catAgri: 'कृषिः', catHealth: 'स्वास्थ्यम्', catEdu: 'शिक्षा', catSchemes: 'सर्वकारयोजना', greeting: 'नमस्ते!', welcomeMsg: 'अहं GramAI अस्मि। कृषि-स्वास्थ्य-शिक्षा-विषये पृच्छतु।', welcomeHint: 'वदतु वा लिखतु।', inputPlaceholder: 'प्रश्नं लिखतु...', online: 'ऑनलाइन', offline: 'ऑफलाइन', speak: 'वदतु...', recognizing: 'अभिज्ञानम्...', recognized: 'अभिज्ञातम्', noSpeech: 'अभिज्ञानं न जातम्।', voiceUnavailable: 'वाक् सेवा नास्ति।', micUnavailable: 'माइक नास्ति', error: 'किञ्चित् दोषः।', allTopics: 'सर्वे विषयाः', topicSelected: 'विषयः चितः', llmUnavailable: 'AI मॉडल नास्ति।', langChanged: 'भाषा परिवर्तिता', source: 'स्रोतः', installTitle: 'GramAI स्थापयतु', installDesc: 'अनुप्रयोगं स्थापयतु', installBtn: 'स्थापयतु', quickWheat: 'गोधूमः', quickPM: 'PM-KISAN', quickFever: 'ज्वरः', quickScholar: 'छात्रवृत्तिः', quickOrganic: 'जैविककृषिः', quickAyush: 'आयुष्मान्' },
  // Manipuri (Meitei)
  mni: { loading: 'GramAI load touri...', subtitle: 'Offline AI pukreibiriba', selectTopic: 'Wahang thourang', catAgri: 'Louthok', catHealth: 'Haksel', catEdu: 'Tamna-Tamshi', catSchemes: 'Sarkar scheme', greeting: 'Khurumjari!', welcomeMsg: 'Eina GramAI ni. Louthok, haksel, tamna-tamshi maramda hanganu.', welcomeHint: 'Wafu ntraga ijanu.', inputPlaceholder: 'Wahang eejanu...', online: 'Online', offline: 'Offline', speak: 'Wafu...', recognizing: 'Khangdokpi...', recognized: 'Khangdokle', noSpeech: 'Khangdokpa ngamde.', voiceUnavailable: 'Voice phangde.', micUnavailable: 'Mic leite', error: 'Amasung thouram.', allTopics: 'Topics pumnamak', topicSelected: 'Topic setkhille', llmUnavailable: 'AI model leite.', langChanged: 'Lon hongdokle', source: 'Mapu', installTitle: 'GramAI Install', installDesc: 'App install tou', installBtn: 'Install', quickWheat: 'Gehun', quickPM: 'PM-KISAN', quickFever: 'Fever', quickScholar: 'Scholarship', quickOrganic: 'Organic', quickAyush: 'Ayushman' },
  // Sindhi
  sd: { loading: 'GramAI لوڊ ٿي رهيو آهي...', subtitle: 'آف لائن AI مددگار', selectTopic: 'موضوع چونڊيو', catAgri: 'زراعت', catHealth: 'صحت', catEdu: 'تعليم', catSchemes: 'سرڪاري اسڪيم', greeting: '!سلام', welcomeMsg: 'مان GramAI آهيان. زراعت، صحت، تعليم بابت پڇو.', welcomeHint: 'ڳالهائي يا لکي پڇو.', inputPlaceholder: '...سوال لکو', online: 'آنلائن', offline: 'آف لائن', speak: '...ڳالهايو', recognizing: '...سڃاڻپ ٿي رهي آهي', recognized: 'سڃاتو', noSpeech: 'سڃاڻپ نه ٿي سگهي.', voiceUnavailable: 'وائس سروس ناهي.', micUnavailable: 'مائڪ ناهي', error: 'غلطي ٿي.', allTopics: 'سڀ موضوع', topicSelected: 'موضوع چونڊيو', llmUnavailable: 'AI ماڊل ناهي.', langChanged: 'ٻولي بدلي', source: 'ذريعو', installTitle: 'GramAI انسٽال', installDesc: 'ايپ انسٽال ڪريو', installBtn: 'انسٽال', quickWheat: 'ڪڻڪ', quickPM: 'PM-KISAN', quickFever: 'تاپ', quickScholar: 'وظيفو', quickOrganic: 'آرگينڪ', quickAyush: 'آيوشمان' },
  // Kashmiri
  ks: { loading: 'GramAI لوڈ گَژھان...', subtitle: 'آف لائن AI مددگار', selectTopic: 'موضوع چُنو', catAgri: 'کاشتکاری', catHealth: 'صحت', catEdu: 'تعلیم', catSchemes: 'سرکاری سکیم', greeting: '!آداب', welcomeMsg: 'بہٕ GramAI چھُس۔ کاشتکاری، صحت، تعلیم بارَس پرُچھو۔', welcomeHint: 'بولِو یا لیکھِو سوال۔', inputPlaceholder: '...سوال لیکھو', online: 'آنلائن', offline: 'آف لائن', speak: '...بولو', recognizing: 'پَہچان...', recognized: 'پَہچان', noSpeech: 'پَہچان نہٕ آو۔', voiceUnavailable: 'وائس سروس نہٕ۔', micUnavailable: 'مائک نہٕ', error: 'غلطی آو۔', allTopics: 'تمام موضوعات', topicSelected: 'موضوع چُنمُت', llmUnavailable: 'AI ماڈل نہٕ۔', langChanged: 'زبان بدلمُت', source: 'ماخذ', installTitle: 'GramAI انسٹال', installDesc: 'ایپ انسٹال کرو', installBtn: 'انسٹال', quickWheat: 'کنک', quickPM: 'PM-KISAN', quickFever: 'تاو', quickScholar: 'وظیفہ', quickOrganic: 'آرگینک', quickAyush: 'آیوشمان' },
  // Bodo
  bodo: { loading: 'GramAI load जाबाय...', subtitle: 'Offline AI गोहो', selectTopic: 'बिथांखि सायख', catAgri: 'हालुआ', catHealth: 'देहा', catEdu: 'रोंथाइ', catSchemes: 'सरकारनि फारि', greeting: 'मोजां दं!', welcomeMsg: 'आं GramAI। हालुआ, देहा, रोंथाइ बिथांखिनि सोंनाय हो।', welcomeHint: 'राव बा लिर सोंनाय हो।', inputPlaceholder: 'सोंनाय लिर हो...', online: 'Online', offline: 'Offline', speak: 'राव हो...', recognizing: 'मिथिं दं...', recognized: 'मिथिनांनाय', noSpeech: 'मिथि मोनाखै।', voiceUnavailable: 'Voice गैया।', micUnavailable: 'Mic गैया', error: 'गोरोन्थि।', allTopics: 'गासै बिथां', topicSelected: 'बिथां सायखनाय', llmUnavailable: 'AI model गैया।', langChanged: 'रावनि सोलाय', source: 'जायगा', installTitle: 'GramAI Install', installDesc: 'App install खालाम', installBtn: 'Install', quickWheat: 'गोधुम', quickPM: 'PM-KISAN', quickFever: 'मोदाइ', quickScholar: 'Scholarship', quickOrganic: 'Organic', quickAyush: 'Ayushman' },
  // Santali
  sat: { loading: 'GramAI load landa...', subtitle: 'Offline AI sahay', selectTopic: 'Bisoy bach koa', catAgri: 'Disom reyak', catHealth: 'Jiwi reyak', catEdu: 'Ol chiki', catSchemes: 'Sarkar jojha', greeting: 'Johar!', welcomeMsg: 'Ing GramAI kanae. Disom, jiwi, ol chiki sanan koa.', welcomeHint: 'Rora ba olpe sanan koa.', inputPlaceholder: 'Sanan ol koa...', online: 'Online', offline: 'Offline', speak: 'Rora...', recognizing: 'Chinhatana...', recognized: 'Chinhatena', noSpeech: 'Chinhat ban darae.', voiceUnavailable: 'Voice banuq.', micUnavailable: 'Mic banuq', error: 'Bhul hoeena.', allTopics: 'Joto bisoy', topicSelected: 'Bisoy bachhena', llmUnavailable: 'AI model banuq.', langChanged: 'Ror badloena', source: 'Mul', installTitle: 'GramAI Install', installDesc: 'App install koa', installBtn: 'Install', quickWheat: 'Gahum', quickPM: 'PM-KISAN', quickFever: 'Rua', quickScholar: 'Scholarship', quickOrganic: 'Organic', quickAyush: 'Ayushman' },
};

// Native script names for language selector
export const LANG_NAMES = {
  hi: 'हिंदी', en: 'English', hg: 'Hinglish', ta: 'தமிழ்', te: 'తెలుగు',
  bn: 'বাংলা', mr: 'मराठी', gu: 'ગુજરાતી', kn: 'ಕನ್ನಡ', ml: 'മലയാളം',
  pa: 'ਪੰਜਾਬੀ', ur: 'اردو', or: 'ଓଡ଼ିଆ', as: 'অসমীয়া', ne: 'नेपाली',
  kok: 'कोंकणी', doi: 'डोगरी', mai: 'मैथिली', sa: 'संस्कृतम्',
  mni: 'মৈতৈলোন্', sd: 'سنڌي', ks: 'کٲشُر', bodo: 'बड़ो', sat: 'ᱥᱟᱱᱛᱟᱲᱤ',
};

// English names for display
export const LANG_ENGLISH = {
  hi: 'Hindi', en: 'English', hg: 'Hinglish', ta: 'Tamil', te: 'Telugu',
  bn: 'Bengali', mr: 'Marathi', gu: 'Gujarati', kn: 'Kannada', ml: 'Malayalam',
  pa: 'Punjabi', ur: 'Urdu', or: 'Odia', as: 'Assamese', ne: 'Nepali',
  kok: 'Konkani', doi: 'Dogri', mai: 'Maithili', sa: 'Sanskrit',
  mni: 'Manipuri', sd: 'Sindhi', ks: 'Kashmiri', bodo: 'Bodo', sat: 'Santali',
};

// Speech recognition / TTS language codes
export const TTS_CODES = {
  hi: 'hi-IN', en: 'en-IN', hg: 'hi-IN', ta: 'ta-IN', te: 'te-IN',
  bn: 'bn-IN', mr: 'mr-IN', gu: 'gu-IN', kn: 'kn-IN', ml: 'ml-IN',
  pa: 'pa-IN', ur: 'ur-IN', or: 'or-IN', as: 'as-IN', ne: 'ne-NP',
  kok: 'kok-IN', doi: 'doi-IN', mai: 'mai-IN', sa: 'sa-IN',
  mni: 'mni-IN', sd: 'sd-IN', ks: 'ks-IN', bodo: 'brx-IN', sat: 'sat-IN',
};

export default TRANSLATIONS;
